version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./frontend/dist:/app/dist
    depends_on:
      - api
      - frontend
    networks:
      - gallia_network

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./api:/app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/galliatech
    command: sh -c "npm install && npm start"
    depends_on:
      - mongodb
    networks:
      - gallia_network

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=https://api.galliatech.com
    command: sh -c "npm install && npm run build"
    networks:
      - gallia_network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - gallia_network

networks:
  gallia_network:
    driver: bridge

volumes:
  mongodb_data: